---  
# Analyzing Patient Data  
teaching: 40  
exercises: 20  
questions:  
- "How can I process tabular data files in Python?"  
objectives:  
- "Explain what a library is and what libraries are used for."  
- "Import a Python library and use the functions it contains."  
- "Read tabular data from a file into a program."  
- "Select individual values and subsections from data."  
- "Perform operations on arrays of data."  
keypoints:  
- "Import a library into a program using `import libraryname`."  
- "Use the `numpy` library to work with arrays in Python."  
- "The expression `array.shape` gives the shape of an array."  
- "Use `array[x, y]` to select a single element from a 2D array."  
- "Array indices start at 0, not 1."  
- "Use `low:high` to specify a `slice` that includes the indices from `low` to `high-1`."  
- "Use `# some kind of explanation` to add comments to programs."  
- "Use `numpy.mean(array)`, `numpy.max(array)`, and `numpy.min(array)` to calculate simple statistics."  
- "Use `numpy.mean(array, axis=0)` or `numpy.mean(array, axis=1)` to calculate statistics across the specified axis."  
---  

Words are useful, but what's more useful are the sentences and stories we build with them.  
Similarly, while a lot of powerful, general tools are built into Python,  
specialized tools built up from these basic units live in  
<span style="color:red" title="A family of code units (functions, classes, variables) that implement a set of  
related tasks.">libraries</span>  
that can be called upon when needed.  

## Loading data into Python  

To begin processing inflammation data, we need to load it into Python.  
We can do that using a library called  
[NumPy](http://docs.scipy.org/doc/numpy/ "NumPy Documentation")  
In general, you should use this library when you want to do fancy things with lots of numbers,  
especially if you have matrices or arrays. To tell Python that we'd like to start using NumPy,  
we need to <span style="color:red" title="To load a library into a program.">import</span>  


In [1]:
import numpy

Importing a library is like getting a piece of lab equipment out of a storage locker and setting it  
up on the bench. Libraries provide additional functionality to the basic Python package, much like  
a new piece of equipment adds functionality to a lab space. Just like in the lab, importing too  
many libraries can sometimes complicate and slow down your programs - so we only import what we  
need for each program.  

Once we've imported the library, we can ask the library to read our data file for us:  


In [1]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],       [ 0.,  1.,  2., ...,  1.,  0.,  1.],       [ 0.,  1.,  1., ...,  2.,  1.,  1.],       ...,       [ 0.,  1.,  1., ...,  1.,  1.,  1.],       [ 0.,  0.,  0., ...,  0.,  2.,  0.],       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

The expression `numpy.loadtxt(...)` is a <span style="color:red" title="A use of a function in another piece of software.">function call</span>  
that asks Python to run the <span style="color:red" title="A named group of instructions that is executed when the function's name is used in  
the code. Occurrence of a function name in the code is a function call.  
Functions may process input arguments and return the result back. Functions  
may also be used for logically grouping together pieces of code. In such cases, they don't  
need to return any meaningful value and can be written without the  
`return` statement completely.  
Such functions return a special value `None`, which is a way of saying "nothing" in Python.">function</span>  
belongs to the `numpy` library. This <span style="color:red" title="A two-part notation used in many programming languages  
in which `thing.component` refers to the `component` belonging to `thing`.">dotted notation</span>  
is used everywhere in Python: the thing that appears before the dot contains the thing that  
appears after.  

As an example, John Smith is the John that belongs to the Smith family.  
We could use the dot notation to write his name `smith.john`,  
just as `loadtxt` is a function that belongs to the `numpy` library.  

`numpy.loadtxt` has two <span style="color:red" title="A variable named in the function's declaration that is used to  
hold a value passed into the call.  
The term is often used interchangeably (and inconsistently) with argument.">parameters</span>  
we want to read and the <span style="color:red" title="A character or characters used to separate individual values,  
such as the commas between columns in a CSV file.">delimiter</span>  
a line. These both need to be character strings (or <span style="color:red" title="Short for "character string",  
a sequence of zero or more characters.">strings</span>  
for short), so we put them in quotes.  

Since we haven't told it to do anything else with the function's output,  
the <span style="color:red" title="Interactive computational environment accessed via your web browser, in which you can write   
and execute Python code and combine it with explanatory text, mathematics and visualizations.  
Examples are IPython or Jupyter notebooks.">notebook</span>  
In this case,  
that output is the data we just loaded.  
By default,  
only a few rows and columns are shown  
(with `...` to omit elements when displaying big arrays).  
Note that, to save space when displaying NumPy arrays, Python does not show us trailing zeros, so `1.0` becomes `1.`.  


> ## Importing libraries with shortcuts  
>  
> In this lesson we use the `import numpy` <span style="color:red" title="The rules that define how code must be written for a computer to understand.">syntax</span>  
> However, shortcuts such as `import numpy as np` are frequently used.  Importing NumPy this way means that after the  
> inital import, rather than writing `numpy.loadtxt(...)`, you can now write `np.loadtxt(...)`. Some  
> people prefer this as it is quicker to type and results in shorter lines of code - especially for libraries  
> with long names! You will frequently see Python code online using a NumPy function with `np`, and it's  
> because they've used this shortcut. It makes no difference which approach you choose to take, but you must be  
> consistent as if you use `import numpy as np` then `numpy.loadtxt(...)` will not work, and you must use `np.loadtxt(...)`  
> instead. Because of this, when working with other people it is important you agree on how libraries are imported.  


Our call to `numpy.loadtxt` read our file  
but didn't save the data in memory.  
To do that,  
we need to assign the array to a variable. In a similar manner to how we assign a single  
value to a variable, we can also assign an array of values to a variable using the same syntax.  
Let's re-run `numpy.loadtxt` and save the returned data:  


In [1]:
data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

This statement doesn't produce any output because we've assigned the output to the variable `data`.  
If we want to check that the data have been loaded,  
we can print the variable's value:  


In [1]:
print(data)

[[ 0.  0.  1. ...,  3.  0.  0.] [ 0.  1.  2. ...,  1.  0.  1.] [ 0.  1.  1. ...,  2.  1.  1.] ..., [ 0.  1.  1. ...,  1.  1.  1.] [ 0.  0.  0. ...,  0.  2.  0.] [ 0.  0.  1. ...,  1.  1.  0.]]

Now that the data are in memory,  
we can manipulate them.  
First,  
let's ask what <span style="color:red" title="The classification of something in a program (for example, the contents of a variable)  
as a kind of number (e.g. floating-point, integer),  
string, or something else.">type</span>  


In [1]:
print(type(data))

<class 'numpy.ndarray'>

The output tells us that `data` currently refers to  
an N-dimensional array, the functionality for which is provided by the NumPy library.  
These data correspond to arthritis patients' inflammation.  
The rows are the individual patients, and the columns  
are their daily inflammation measurements.  


> ## Data Type  
>  
> A Numpy array contains one or more elements  
> of the same type. The `type` function will only tell you that  
> a variable is a NumPy array but won't tell you the type of  
> thing inside the array.  
> We can find out the type  
> of the data contained in the NumPy array.  
>  
> ---  
```python
> print(data.dtype)  
```
> ---  
> 
>  
> ---  
```python
> float64  
```
> ---  
> 
>  
> This tells us that the NumPy array's elements are  
> <span style="color:red" title="A number containing a fractional part and an exponent.  
See also: integer.">floating-point numbers</span>  


With the following command, we can see the array's <span style="color:red" title="An array's dimensions, represented as a vector.  
For example, a 5×3 array's shape is `(5,3)`.">shape</span>  


In [1]:
print(data.shape)

(60, 40)

The output tells us that the `data` array variable contains 60 rows and 40 columns. When we  
created the variable `data` to store our arthritis data, we did not only create the array; we also  
created information about the array, called <span style="color:red" title="A variable contained within an object.">members</span>  
attributes. This extra information describes `data` in the same way an adjective describes a noun.  
`data.shape` is an attribute of `data` which describes the dimensions of `data`. We use the same  
dotted notation for the attributes of variables that we use for the functions in libraries because  
they have the same part-and-whole relationship.  

If we want to get a single number from the array, we must provide an  
<span style="color:red" title="A subscript that specifies the location of a single value in a collection,  
such as a single pixel in an image.">index</span>  
do in math when referring to an element of a matrix.  Our inflammation data has two dimensions, so  
we will need to use two indices to refer to one specific value:  


In [1]:
print('first value in data:', data[0, 0])

first value in data: 0.0

In [1]:
print('middle value in data:', data[30, 20])

middle value in data: 13.0

The expression `data[30, 20]` accesses the element at row 30, column 20. While this expression may  
not surprise you,  
 `data[0, 0]` might.  
Programming languages like Fortran, MATLAB and R start counting at 1  
because that's what human beings have done for thousands of years.  
Languages in the C family (including C++, Java, Perl, and Python) count from 0  
because it represents an offset from the first value in the array (the second  
value is offset by one index from the first value). This is closer to the way  
that computers represent arrays (if you are interested in the historical  
reasons behind counting indices from zero, you can read  
[Mike Hoye's blog post](http://exple.tive.org/blarg/2013/10/22/citation-needed/)  
As a result,  
if we have an M×N array in Python,  
its indices go from 0 to M-1 on the first axis  
and 0 to N-1 on the second.  
It takes a bit of getting used to,  
but one way to remember the rule is that  
the index is how many steps we have to take from the start to get the item we want.  

> <img src=fig/python-zero-index.png>Zero Index  


> ## In the Corner  
>  
> What may also surprise you is that when Python displays an array,  
> it shows the element with index `[0, 0]` in the upper left corner  
> rather than the lower left.  
> This is consistent with the way mathematicians draw matrices  
> but different from the Cartesian coordinates.  
> The indices are (row, column) instead of (column, row) for the same reason,  
> which can be confusing when plotting data.  


## Slicing data  
An index like `[30, 20]` selects a single element of an array,  
but we can select whole sections as well.  
For example,  
we can select the first ten days (columns) of values  
for the first four patients (rows) like this:  


In [1]:
print(data[0:4, 0:10])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.] [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6.] [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.] [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7.]]

The <span style="color:red" title="A regular subsequence of a larger sequence,  
such as the first five elements or every second element.">slice</span>  
including, index 4". Again, the up-to-but-not-including takes a bit of getting used to, but the  
rule is that the difference between the upper and lower bounds is the number of values in the slice.  

We don't have to start slices at 0:  


In [1]:
print(data[5:10, 0:10])

[[ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.] [ 0.  0.  2.  2.  4.  2.  2.  5.  5.  8.] [ 0.  0.  1.  2.  3.  1.  2.  3.  5.  3.] [ 0.  0.  0.  3.  1.  5.  6.  5.  5.  8.] [ 0.  1.  1.  2.  1.  3.  5.  3.  5.  8.]]

We also don't have to include the upper and lower bound on the slice.  If we don't include the lower  
bound, Python uses 0 by default; if we don't include the upper, the slice runs to the end of the  
axis, and if we don't include either (i.e., if we use ':' on its own), the slice includes  
everything:  


In [1]:
small = data[:3, 36:]
print('small is:')
print(small)

small is:[[ 2.  3.  0.  0.] [ 1.  1.  0.  1.] [ 2.  2.  1.  1.]]

## Analyzing data  

NumPy has several useful functions that take an array as input to perform operations on its values.  
If we want to find the average inflammation for all patients on  
all days, for example, we can ask NumPy to compute `data`'s mean value:  


In [1]:
print(numpy.mean(data))

6.14875

`mean` is a <span style="color:red" title="A named group of instructions that is executed when the function's name is used in  
the code. Occurrence of a function name in the code is a function call.  
Functions may process input arguments and return the result back. Functions  
may also be used for logically grouping together pieces of code. In such cases, they don't  
need to return any meaningful value and can be written without the  
`return` statement completely.  
Such functions return a special value `None`, which is a way of saying "nothing" in Python.">function</span>  
an array as an <span style="color:red" title="A value given to a function or program when it runs.  
The term is often used interchangeably (and inconsistently) with parameter.">argument</span>  


> ## Not All Functions Have Input  
>  
> Generally, a function uses inputs to produce outputs.  
> However, some functions produce outputs without  
> needing any input. For example, checking the current time  
> doesn't require any input.  
>  
> ---  
```python
> import time  
> print(time.ctime())  
```
> ---  
> 
>  
> ---  
```python
> Sat Mar 26 13:07:33 2016  
```
> ---  
> 
>  
> For functions that don't take in any arguments,  
> we still need parentheses (`()`)  
> to tell Python to go and do something for us.  


Let's use three other NumPy functions to get some descriptive values about the dataset.  
We'll also use multiple assignment,  
a convenient Python feature that will enable us to do this all in one line.  


In [1]:
maxval, minval, stdval = numpy.max(data), numpy.min(data), numpy.std(data)

print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

maximum inflammation: 20.0minimum inflammation: 0.0standard deviation: 4.61383319712

> ## Mystery Functions in IPython  
>  
> How did we know what functions NumPy has and how to use them?  
> If you are working in IPython or in a Jupyter Notebook, there is an easy way to find out.  
> If you type the name of something followed by a dot, then you can use tab completion  
> (e.g. type `numpy.` and then press <kbd>Tab</kbd>)  
> to see a list of all functions and attributes that you can use. After selecting one, you  
> can also add a question mark (e.g. `numpy.cumprod?`), and IPython will return an  
> explanation of the method! This is the same as doing `help(numpy.cumprod)`.  
> Similarly, if you are using the "plain vanilla" Python interpreter, you can type `numpy.`  
> and press the <kbd>Tab</kbd> key twice for a listing of what is available. You can then use the  
> `help()` function to see an explanation of the function you're interested in,  
> for example: `help(numpy.cumprod)`.  


When analyzing data, though,  
we often want to look at variations in statistical values,  
such as the maximum inflammation per patient  
or the average inflammation per day.  
One way to do this is to create a new temporary array of the data we want,  
then ask it to do the calculation:  


In [1]:
patient_0 = data[0, :] # 0 on the first axis (rows), everything on the second (columns)
print('maximum inflammation for patient 0:', numpy.max(patient_0))

maximum inflammation for patient 0: 18.0

Everything in a line of code following the '#' symbol is a  
<span style="color:red" title="A remark in a program that is intended to help human readers understand what is going on,  
but is ignored by the computer.  
Comments in Python, R, and the Unix shell start with a `#` character and  
run to the end of the line;  
comments in SQL start with `--`,  
and other languages have other conventions.">comment</span>  
Comments allow programmers to leave explanatory notes for other  
programmers or their future selves.  

We don't actually need to store the row in a variable of its own.  
Instead, we can combine the selection and the function call:  


In [1]:
print('maximum inflammation for patient 2:', numpy.max(data[2, :]))

maximum inflammation for patient 2: 19.0

What if we need the maximum inflammation for each patient over all days (as in the  
next diagram on the left) or the average for each day (as in the  
diagram on the right)? As the diagram below shows, we want to perform the  
operation across an axis:  

![Per-patient maximum inflammation is computed row-wise across all columns using numpy.max(data, axis=1).  
Per-day average inflammation is computed column-wise across all rows using numpy.mean(data, axis=0).](../fig/python-operations-across-axes.png)  

To support this functionality,  
most array functions allow us to specify the axis we want to work on.  
If we ask for the average across axis 0 (rows in our 2D example),  
we get:  


In [1]:
print(numpy.mean(data, axis=0))

[  0.           0.45         1.11666667   1.75         2.43333333   3.15   3.8          3.88333333   5.23333333   5.51666667   5.95         5.9   8.35         7.73333333   8.36666667   9.5          9.58333333  10.63333333  11.56666667  12.35        13.25        11.96666667  11.03333333  10.16666667  10.           8.66666667   9.15         7.25   7.33333333   6.58333333   6.06666667   5.95         5.11666667   3.6   3.3          3.56666667   2.48333333   1.5          1.13333333   0.56666667]

As a quick check,  
we can ask this array what its shape is:  


In [1]:
print(numpy.mean(data, axis=0).shape)

(40,)

The expression `(40,)` tells us we have an N×1 vector,  
so this is the average inflammation per day for all patients.  
If we average across axis 1 (columns in our 2D example), we get:  


In [1]:
print(numpy.mean(data, axis=1))

[ 5.45   5.425  6.1    5.9    5.55   6.225  5.975  6.65   6.625  6.525  6.775  5.8    6.225  5.75   5.225  6.3    6.55   5.7    5.85   6.55  5.775  5.825  6.175  6.1    5.8    6.425  6.05   6.025  6.175  6.55  6.175  6.35   6.725  6.125  7.075  5.725  5.925  6.15   6.075  5.75  5.975  5.725  6.3    5.9    6.75   5.925  7.225  6.15   5.95   6.275  5.7  6.1    6.825  5.975  6.725  5.7    6.25   6.4    7.05   5.9  ]

which is the average inflammation per patient across all days.  


## Slicing Strings  

A section of an array is called a <span style="color:red" title="A regular subsequence of a larger sequence,  
such as the first five elements or every second element.">slice</span>  
We can take slices of character strings as well:  

---  
```python
element = 'oxygen'  
print('first three characters:', element[0:3])  
print('last three characters:', element[3:6])  
```
---  


---  
```python
first three characters: oxy  
last three characters: gen  
```
---  


What is the value of `element[:4]`?  
What about `element[4:]`?  
Or `element[:]`?  

<details>  
<summary><b> Solution</b></summary>  

---  
```python
oxyg  
en  
oxygen  
```
---  

</details>  

What is `element[-1]`?  
What is `element[-2]`?  

<details>  
<summary><b> Solution</b></summary>  

---  
```python
n  
e  
```
---  

</details>  

Given those answers,  
explain what `element[1:-1]` does.  

<details>  
<summary><b> Solution</b></summary>  

Creates a substring from index 1 up to (not including) the final index,  
effectively removing the first and last letters from 'oxygen'  
</details>  

How can we rewrite the slice for getting the last three characters of `element`,  
so that it works even if we assign a different string to `element`?  
Test your solution with the following strings: `carpentry`, `clone`, `hi`.  

<details>  
<summary><b> Solution</b></summary>  

---  
```python
element = 'oxygen'  
print('last three characters:', element[-3:])  
element = 'carpentry'  
print('last three characters:', element[-3:])  
element = 'clone'  
print('last three characters:', element[-3:])  
element = 'hi'  
print('last three characters:', element[-3:])  
```
---  

---  
```python
last three characters: gen  
last three characters: try  
last three characters: one  
last three characters: hi  
```
---  

</details>  


## Thin Slices  

The expression `element[3:3]` produces an <span style="color:red" title="A character string containing no characters,  
often thought of as the "zero" of text.">empty string</span>  
i.e., a string that contains no characters.  
If `data` holds our array of patient data,  
what does `data[3:3, 4:4]` produce?  
What about `data[3:3, :]`?  

<details>  
<summary><b> Solution</b></summary>  

---  
```python
array([], shape=(0, 0), dtype=float64)  
array([], shape=(0, 40), dtype=float64)  
```
---  

</details>  


## Stacking Arrays  

Arrays can be concatenated and stacked on top of one another,  
using NumPy's `vstack` and `hstack` functions for vertical and horizontal stacking, respectively.  

---  
```python
import numpy  

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])  
print('A = ')  
print(A)  

B = numpy.hstack([A, A])  
print('B = ')  
print(B)  

C = numpy.vstack([A, A])  
print('C = ')  
print(C)  
```
---  


---  
```python
A =  
[[1 2 3]  
[4 5 6]  
[7 8 9]]  
B =  
[[1 2 3 1 2 3]  
[4 5 6 4 5 6]  
[7 8 9 7 8 9]]  
C =  
[[1 2 3]  
[4 5 6]  
[7 8 9]  
[1 2 3]  
[4 5 6]  
[7 8 9]]  
```
---  


Write some additional code that slices the first and last columns of `A`,  
and stacks them into a 3x2 array.  
Make sure to `print` the results to verify your solution.  

<details>  
<summary><b> Solution</b></summary>  


A 'gotcha' with array indexing is that singleton dimensions  
are dropped by default. That means `A[:, 0]` is a one dimensional  
array, which won't stack as desired. To preserve singleton dimensions,  
the index itself can be a slice or array. For example, `A[:, :1]` returns  
a two dimensional array with one singleton dimension (i.e. a column  
vector).  

---  
```python
D = numpy.hstack((A[:, :1], A[:, -1:]))  
print('D = ')  
print(D)  
```
---  


---  
```python
D =  
[[1 3]  
[4 6]  
[7 9]]  
```
---  

</details>  

<details>  
<summary><b> Solution</b></summary>  


An alternative way to achieve the same result is to use Numpy's  
delete function to remove the second column of A.  

---  
```python
D = numpy.delete(A, 1, 1)  
print('D = ')  
print(D)  
```
---  


---  
```python
D =  
[[1 3]  
[4 6]  
[7 9]]  
```
---  

</details>  


## Change In Inflammation  

The patient data is _longitudinal_ in the sense that each row represents a  
series of observations relating to one individual.  This means that  
the change in inflammation over time is a meaningful concept.  
Let's find out how to calculate changes in the data contained in an array  
with NumPy.  

The `numpy.diff()` function takes an array and returns the differences  
between two successive values. Let's use it to examine the changes  
each day across the first week of patient 3 from our inflammation dataset.  

---  
```python
patient3_week1 = data[3, :7]  
print(patient3_week1)  
```
---  


---  
```python
[0. 0. 2. 0. 4. 2. 2.]  
```
---  


Calling `numpy.diff(patient3_week1)` would do the following calculations  

---  
```python
[ 0 - 0, 2 - 0, 0 - 2, 4 - 0, 2 - 4, 2 - 2 ]  
```
---  


and return the 6 difference values in a new array.  

---  
```python
numpy.diff(patient3_week1)  
```
---  


---  
```python
array([ 0.,  2., -2.,  4., -2.,  0.])  
```
---  


Note that the array of differences is shorter by one element (length 6).  

When calling `numpy.diff` with a multi-dimensional array, an `axis` argument may  
be passed to the function to specify which axis to process. When applying  
`numpy.diff` to our 2D inflammation array `data`, which axis would we specify?  

<details>  
<summary><b> Solution</b></summary>  

Since the row axis (0) is patients, it does not make sense to get the  
difference between two arbitrary patients. The column axis (1) is in  
days, so the difference is the change in inflammation -- a meaningful  
concept.  

---  
```python
numpy.diff(data, axis=1)  
```
---  

</details>  

If the shape of an individual data file is `(60, 40)` (60 rows and 40  
columns), what would the shape of the array be after you run the `diff()`  
function and why?  

<details>  
<summary><b> Solution</b></summary>  

The shape will be `(60, 39)` because there is one fewer difference between  
columns than there are columns in the data.  
</details>  

How would you find the largest change in inflammation for each patient? Does  
it matter if the change in inflammation is an increase or a decrease?  

<details>  
<summary><b> Solution</b></summary>  

By using the `numpy.max()` function after you apply the `numpy.diff()`  
function, you will get the largest difference between days.  

---  
```python
numpy.max(numpy.diff(data, axis=1), axis=1)  
```
---  


---  
```python
array([  7.,  12.,  11.,  10.,  11.,  13.,  10.,   8.,  10.,  10.,   7.,  
7.,  13.,   7.,  10.,  10.,   8.,  10.,   9.,  10.,  13.,   7.,  
12.,   9.,  12.,  11.,  10.,  10.,   7.,  10.,  11.,  10.,   8.,  
11.,  12.,  10.,   9.,  10.,  13.,  10.,   7.,   7.,  10.,  13.,  
12.,   8.,   8.,  10.,  10.,   9.,   8.,  13.,  10.,   7.,  10.,  
8.,  12.,  10.,   7.,  12.])  
```
---  


If inflammation values *decrease* along an axis, then the difference from  
one element to the next will be negative. If  
you are interested in the **magnitude** of the change and not the  
direction, the `numpy.absolute()` function will provide that.  

Notice the difference if you get the largest _absolute_ difference  
between readings.  

---  
```python
numpy.max(numpy.absolute(numpy.diff(data, axis=1)), axis=1)  
```
---  


---  
```python
array([ 12.,  14.,  11.,  13.,  11.,  13.,  10.,  12.,  10.,  10.,  10.,  
12.,  13.,  10.,  11.,  10.,  12.,  13.,   9.,  10.,  13.,   9.,  
12.,   9.,  12.,  11.,  10.,  13.,   9.,  13.,  11.,  11.,   8.,  
11.,  12.,  13.,   9.,  10.,  13.,  11.,  11.,  13.,  11.,  13.,  
13.,  10.,   9.,  10.,  10.,   9.,   9.,  13.,  10.,   9.,  10.,  
11.,  13.,  10.,  10.,  12.])  
```
---  


</details>  
